dataset:
  folder_location : datasets/pcd_files/
  pcd:
    file_name       : Div02k_02 #file_name       : Div02k_02
    file_type       : .pcd

output:
  folder_location : /output
  topView:
    folder_location : topView
  sideView:
    folder_location : sideView

yolov5:
  yolov5_pth: "yolov5"
  topView:
    axis      : "z"
    imgSize   : [640, 640]
    model_pth : "model_weights/topDetec640.pt"
    stepsize  : 0.1
  sideView:
    axis    : "x"
    imgSize : [320, 768]
    model_pth : "model_weights/v14_side.pt"
    stepsize : 0.02
    minNoPoints : 1500
    imgSizeTall : [320, 1280]